### PR TITLE
 fix: auth issues

### LINKED ISSUE #200: Bug: Schema can be fetched with invalid auth token
Currently the graphQL schema can be fetched without a valid auth token. (see picture)
This is because the gateway does not check the token with the cluster in that case.

I guess a simple SelfSubjectReview or similar simple request to the cluster could solve that?

Image

If a gateway is publicly available, this could give an attacker information about the clusters resources and controllers.

### PR DESCRIPTION
**Pull request by vertex451**
Resolves #200 

1. Now, if INTROSPECTION_AUTHENTICATION=true, schema fetching is failing in case of invalid token.
2. Also, in case of invalid token we will not get resources for ClusterAccess and KCP flows.

## Changes
Mostly this two lines does the job:
	req.Header.Del("Authorization")
	req.Header.Set("Authorization", "Bearer "+token)
	
Also, I returned isDiscoveryRequest func to pass the admin rountripper during that request.

## Testing
1. Tested locally with clusterAccess 
2. Tested in local-setup by loading image built locally with the same tag.
Screenshot 2025-07-08 at 18 31 07

### CODE REVIEW

File: gateway/manager/targetcluster/registry.go [hunk 1]
```diff
@@ -218,6 +228,106 @@ func (cr *ClusterRegistry) handleCORS(w http.ResponseWriter, r *http.Request) bo
 	return false
 }
 
+func (cr *ClusterRegistry) validateToken(token string, cluster *TargetCluster) (bool, error) {
```
Comment (vertex451) [inline gateway/manager/targetcluster/registry.go:231]: This function is big and duplicates what we have in roundtripper.
I am trying to simplify it by using rountripper in its request.

**Comment by aaronschweig** [comment]
@n3rdc4ptn could you verify your use-case with this PR to see if it works as intended?

**Comment by aaronschweig** [comment]
@vertex451 can you please make sure the tests are passing?

**Comment by vertex451** [comment]
> @vertex451 can you please make sure the tests are passing?

sure, on it

**Review by aaronschweig — APPROVED** [review]
